application:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

server:
  port: 8080
  servlet:
    context-path: '/api'

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

